name: Scala CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: [v*]

jobs:
  build:
    uses: gfc-collective/gfc-gh-actions-shared/.github/workflows/ci-scala-library.yml@main
